ci: add docker image

diff --git a/week5/apis-fetch-lab/Jenkinsfile b/week5/apis-fetch-lab/Jenkinsfile
--- a/week5/apis-fetch-lab/Jenkinsfile
+++ b/week5/apis-fetch-lab/Jenkinsfile
@@ -1,5 +1,9 @@
 pipeline {
-    agent any
+    agent {
+        docker {
+            image 'node:lts'
+        }
+    }
     environment {
         NODE_ENV = "test"
         BUILD_DIR = "dist"
@@ -15,6 +19,14 @@ pipeline {
             steps {
                 echo "Installing dependencies for ${APP_NAME}..."
                 sh "npm ci"
+                echo "Building application..."
+                sh 'npm run build'
+                echo "Verifying build output"
+                sh '''
+                set -e
+                test -d "${BUILD_DIR}" || { echo "ERROR: build directory not found"; exit 1; }
+                echo "Build output: $(ls ${BUILD_DIR} | wc -l) files in ${BUILD_DIR}/ "
+                '''
             }
         }
         stage("Test"){
@@ -37,6 +49,7 @@ pipeline {
         }
         always {
             echo "Build URL: ${BUILD_URL}"
+            cleanWs()
         }
     }
 }
